version: '3.4'

services:
  phase1algorithmspalindrome:
    image: phase1algorithmspalindrome
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
